"""
AI University - Streamlit entry point.

This file is the "Dashboard" landing page. Additional pages live in
`pages/` and are picked up automatically by Streamlit's native
multipage support (file-based routing - no manual registration needed).
"""

from __future__ import annotations

import streamlit as st

from config import settings
from utils.logging_config import configure_logging

configure_logging()

st.set_page_config(
    page_title="AI University",
    page_icon="🎓",
    layout="wide",
)

st.title("🎓 AI University")
st.caption("Multi-agent system for generating full educational courses.")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Anthropic key", "configured" if settings.has_anthropic else "missing")
with col2:
    st.metric("OpenAI key", "configured" if settings.has_openai else "missing")
with col3:
    st.metric("Environment", settings.app_env.value)

st.divider()

if not (settings.has_anthropic or settings.has_openai):
    st.error(
        "No LLM provider configured. Copy `.env.example` to `.env` and set "
        "ANTHROPIC_API_KEY and/or OPENAI_API_KEY before running a course."
    )
else:
    st.success("At least one LLM provider is configured. You're ready to run a course.")

st.markdown(
    """
    ### Navigate
    Use the sidebar to get to:
    - **Run Course** — kick off a new pipeline run
    - **Agents Status** — see registered agents and what's implemented
    - **File Browser** — inspect files generated by past runs
    - **Settings** — view current configuration (no secrets shown)

    _Phase 1: this shell is functional but the agent chain is still a stub.
    Real agents land in Phase 2._
    """
)
