"""
AI University - Streamlit entry point.

This file is the "Dashboard" landing page. Additional pages live in
`pages/` and are picked up automatically by Streamlit's native
multipage support (file-based routing - no manual registration needed).
"""

from __future__ import annotations

import streamlit as st

import agents  # noqa: F401 - triggers agent registration
from agents.base import list_registered_agents
from config import settings
from utils.logging_config import configure_logging

configure_logging()

st.set_page_config(
    page_title="AI University",
    page_icon="🎓",
    layout="wide",
)

st.title("🎓 AI University")
st.caption("Multi-agent system for generating full educational courses.")

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Anthropic key", "configured" if settings.has_anthropic else "missing")
with col2:
    st.metric("OpenAI key", "configured" if settings.has_openai else "missing")
with col3:
    st.metric("Tavily key", "configured" if settings.tavily_api_key else "missing (search falls back to stub)")
with col4:
    st.metric("Agents registered", len(list_registered_agents()))

st.divider()

if not (settings.has_anthropic or settings.has_openai):
    st.error(
        "No LLM provider configured. Copy `.env.example` to `.env` and set "
        "ANTHROPIC_API_KEY and/or OPENAI_API_KEY before running a course."
    )
else:
    st.success("At least one LLM provider is configured. You're ready to run a course.")

st.markdown(
    """
    ### Navigate
    Use the sidebar to get to:
    - **Run Course** — kick off a new pipeline run, with the Phase 4 reviewer loop and Phase 5 export
    - **Agents Status** — see every registered agent
    - **File Browser** — inspect files generated by past runs
    - **Settings** — view current configuration (no secrets shown)

    ### What's built
    Persona → Research (smolagents + Tavily) → Curriculum → per-lesson content
    agents (Notebook, Code, Diagram, Quiz, Assignment, Speaker Notes), each
    checked by a Reviewer agent that can request revisions, exporting to a
    real `.ipynb` + `.pptx`. Automatic Anthropic ↔ OpenAI failover if a
    provider call fails. See the [README](https://github.com/chaudharyviv/ai-university)
    for what's cut from scope.
    """
)
